// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-challenge-plans.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function publicClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_challenge_plans_default = defineTool({
  name: "list_challenge_plans",
  title: "List challenge plans",
  description: "List the available Prop Gym funded-account challenge plans with pricing, account sizes, profit targets, and drawdown limits. Public, no login required.",
  inputSchema: {
    challenge_type: z.string().optional().describe("Optional filter by challenge type, e.g. one_step, two_step, or instant.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ challenge_type }) => {
    let query = publicClient().from("challenge_plans").select(
      "id, challenge_type, account_size, price_usd, profit_target_phase1, profit_target_phase2, daily_drawdown_limit, overall_drawdown_limit, min_trading_days"
    ).order("price_usd", { ascending: true });
    if (challenge_type) query = query.eq("challenge_type", challenge_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { plans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-trading-accounts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_trading_accounts_default = defineTool2({
  name: "list_my_trading_accounts",
  title: "List my trading accounts",
  description: "List the signed-in user's funded/challenge trading accounts with balance, phase, status, profit progress, and drawdown. Requires login.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("trading_accounts").select(
      "id, account_number, platform, server, balance, phase, status, profit_percent, profit_target, daily_drawdown, overall_drawdown, trading_days, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { accounts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-wallet.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser2(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_wallet_default = defineTool3({
  name: "get_my_wallet",
  title: "Get my wallet",
  description: "Get the signed-in user's Prop Gym wallet: current balance, total earnings, and total withdrawn (USD). Requires login.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("wallets").select("balance, total_earnings, total_withdrawn, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { wallet: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-purchases.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_purchases_default = defineTool4({
  name: "list_my_purchases",
  title: "List my challenge purchases",
  description: "List the signed-in user's challenge purchase orders with status, linked plan, and creation date. Requires login.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("challenge_purchases").select(
      "id, status, transaction_id, discount_code, created_at, challenge_plans(challenge_type, account_size, price_usd)"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { purchases: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mvjiisufjgrnzaqielra";
var mcp_default = defineMcp({
  name: "prop-gym-mcp",
  title: "Prop Gym MCP",
  version: "0.1.0",
  instructions: "Tools for Prop Gym, a proprietary trading platform. Use `list_challenge_plans` to browse funded-account challenges (public). Signed-in users can inspect their trading accounts, wallet, and purchases with the `list_my_*` and `get_my_wallet` tools.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_challenge_plans_default, list_my_trading_accounts_default, get_my_wallet_default, list_my_purchases_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
